import React, {useEffect,useMemo,useState} from 'react';
import {Search,Plus,X,ExternalLink,LogOut,History,Save,Users} from 'lucide-react';
import {supabase,configured} from './supabase';

const CITIES=['Port Richey','New Port Richey','Holiday','Tarpon Springs','Palm Harbor','Dunedin','Oldsmar','Safety Harbor','Clearwater','Clearwater Beach','Indian Rocks Beach','Largo','Belleair Bluffs','Pinellas Park','Seminole','Madeira Beach','Treasure Island','St Petersburg','St Pete Beach'];
const STATUS={not_visited:'待拜访',visited:'已卖进/拜访',follow_up:'需跟进',no_interest:'无意向/暂缓'};
const emptyShop=()=>({name:'',address:'',city:'Clearwater',phone:'',tier:'',status:'not_visited',is_chain:false,chain_name:'',chain_total_stores:'',staff_contact:'',owner_name:'',owner_schedule:'',contact_role:'',store_number:'',restock_status:'',distributor:'',test_case_placed:false,traffic_note:'',brands_note:'',next_plan:'',source_url:''});

function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message)};return <main className="login"><form className="panel" onSubmit={submit}><h1>门店拜访清单</h1><p>Tampa Bay 西岸 · 云端版</p><label>邮箱<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>密码<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{err&&<div className="error">{err}</div>}<button className="primary">登录</button></form></main>}

export default function App(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[shops,setShops]=useState([]),[members,setMembers]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[visits,setVisits]=useState([]),[showHistory,setShowHistory]=useState(false),[visit,setVisit]=useState({visit_date:new Date().toISOString().slice(0,10),units:'',feedback:'',decision_maker:'',restock_status:'',test_case_placed:false,next_plan:''});
 useEffect(()=>{if(!configured){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) loadAll();else{setProfile(null);setShops([])}},[session]);
 async function loadAll(){setLoading(true);const uid=session.user.id;const {data:p,error:pe}=await supabase.from('profiles').select('*').eq('id',uid).single();if(pe){alert(pe.message);setLoading(false);return}setProfile(p);const {data:s,error:se}=await supabase.from('shops').select('*').order('updated_at',{ascending:false});if(se)alert(se.message);else setShops(s||[]);if(p.role==='manager'){const {data:m}=await supabase.from('profiles').select('id,full_name,email,role,active').eq('team_id',p.team_id).order('full_name');setMembers(m||[])}setLoading(false)}
 async function openShop(s){setSelected(s.id);setDraft({...s,chain_total_stores:s.chain_total_stores??''});setShowHistory(false);const {data,error}=await supabase.from('visits').select('*').eq('shop_id',s.id).order('visit_date',{ascending:false}).order('created_at',{ascending:false});if(error)alert(error.message);else setVisits(data||[])}
 function openNew(){setSelected('new');setDraft(emptyShop());setVisits([])}
 async function saveShop(){if(!draft.name.trim())return;const payload={...draft,name:draft.name.trim(),chain_total_stores:draft.chain_total_stores===''?null:Number(draft.chain_total_stores)};delete payload.id;delete payload.created_at;delete payload.updated_at;if(selected==='new'){payload.team_id=profile.team_id;payload.assigned_to=profile.role==='manager'?(draft.assigned_to||profile.id):profile.id;const {error}=await supabase.from('shops').insert(payload);if(error)return alert(error.message)}else{const {error}=await supabase.from('shops').update(payload).eq('id',selected);if(error)return alert(error.message)}setSelected(null);setDraft(null);await loadAll()}
 async function addVisit(){if(selected==='new')return;const payload={shop_id:selected,sales_id:session.user.id,...visit,units:Number(visit.units)||0};const {error}=await supabase.from('visits').insert(payload);if(error)return alert(error.message);await supabase.from('shops').update({status:'visited',restock_status:visit.restock_status||draft.restock_status,test_case_placed:visit.test_case_placed||draft.test_case_placed,next_plan:visit.next_plan||draft.next_plan}).eq('id',selected);setVisit({visit_date:new Date().toISOString().slice(0,10),units:'',feedback:'',decision_maker:'',restock_status:'',test_case_placed:false,next_plan:''});await openShop({...draft,id:selected});await loadAll()}
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return shops.filter(s=>!q||[s.name,s.address,s.city,s.owner_name,s.staff_contact].some(v=>(v||'').toLowerCase().includes(q)))},[shops,search]);
 if(!configured)return <main className="login"><div className="panel"><h1>还差环境变量</h1><p>把 <code>.env.example</code> 复制成 <code>.env</code>，填入你的 Supabase Project URL 和 Publishable key，然后重新启动。</p></div></main>;
 if(loading)return <div className="loading">加载中…</div>; if(!session)return <Login/>;
 return <main className="app"><header><div><h1>门店拜访清单</h1><span>Tampa Bay 西岸</span></div><div className="user"><Users size={15}/>{profile?.full_name||session.user.email}<b>{profile?.role==='manager'?'Manager':'Sales'}</b><button onClick={()=>supabase.auth.signOut()}><LogOut size={15}/>退出</button></div></header>
 <section className="toolbar"><div className="search"><Search size={15}/><input placeholder="搜索店名 / 地址 / 城市 / 联系人" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="primary" onClick={openNew}><Plus size={15}/>添加店铺</button><button disabled title="后续版本：导出今日 Excel">导出今日表格（预留）</button></section>
 {profile?.role==='manager'&&<div className="manager-note">Manager 模式：当前可查看团队全部门店 · {members.length} 个账号</div>}
 <div className="count">共 {filtered.length} 家店铺</div>
 <section>{filtered.map(s=><article className="card" key={s.id} onClick={()=>openShop(s)}><div className="cardtop"><div><strong>{s.name}</strong><small>{s.city}{s.address?` · ${s.address}`:' · 地址待补充'}</small></div><div><span className="chip">{s.tier||'未分级'}</span><span className="chip">{STATUS[s.status]}</span></div></div><div className="meta">{s.owner_name&&<span>老板 {s.owner_name}</span>}{s.distributor&&<span>批发商 {s.distributor}</span>}{s.test_case_placed&&<span>已放 Test Case</span>}</div>{s.brands_note&&<p>{s.brands_note}</p>}{s.next_plan&&<p className="next">下次：{s.next_plan}</p>}</article>)}</section>
 {draft&&<div className="modal" onMouseDown={()=>{setDraft(null);setSelected(null)}}><div className="editor" onMouseDown={e=>e.stopPropagation()}><div className="editorhead"><h2>{selected==='new'?'添加店铺':'编辑店铺'}</h2><button onClick={()=>setDraft(null)}><X size={18}/></button></div>
 <div className="grid"><Field label="店铺名称"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="城市"><select value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}>{CITIES.map(c=><option key={c}>{c}</option>)}</select></Field><Field wide label="地址"><input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></Field><Field label="电话"><input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="评级"><select value={draft.tier} onChange={e=>setDraft({...draft,tier:e.target.value})}>{['','S','A+','A','B'].map(x=><option key={x} value={x}>{x||'未分级'}</option>)}</select></Field><Field label="拜访状态"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="老板 / Decision maker"><input value={draft.owner_name} onChange={e=>setDraft({...draft,owner_name:e.target.value})}/></Field><Field label="员工联系人"><input value={draft.staff_contact} onChange={e=>setDraft({...draft,staff_contact:e.target.value})}/></Field><Field label="老板到店规律"><input value={draft.owner_schedule} onChange={e=>setDraft({...draft,owner_schedule:e.target.value})}/></Field><Field label="主要拿货二级批发商"><input value={draft.distributor} onChange={e=>setDraft({...draft,distributor:e.target.value})}/></Field><Field label="进货情况"><input value={draft.restock_status} onChange={e=>setDraft({...draft,restock_status:e.target.value})}/></Field><Field label="是否放 Test Case"><select value={draft.test_case_placed?'yes':'no'} onChange={e=>setDraft({...draft,test_case_placed:e.target.value==='yes'})}><option value="no">否</option><option value="yes">是</option></select></Field>{profile?.role==='manager'&&<Field label="负责人"><select value={draft.assigned_to||profile.id} onChange={e=>setDraft({...draft,assigned_to:e.target.value})}>{members.filter(m=>m.active).map(m=><option value={m.id} key={m.id}>{m.full_name||m.email} · {m.role}</option>)}</select></Field>}<Field wide label="热卖品牌明细"><textarea value={draft.brands_note} onChange={e=>setDraft({...draft,brands_note:e.target.value})}/></Field><Field wide label="客流 / 位置信息"><textarea value={draft.traffic_note} onChange={e=>setDraft({...draft,traffic_note:e.target.value})}/></Field><Field wide label="下次拜访计划"><input value={draft.next_plan} onChange={e=>setDraft({...draft,next_plan:e.target.value})}/></Field></div>
 {selected!=='new'&&<div className="visitbox"><h3>拜访记录 <small>明面显示最近 3 次</small></h3><div className="visitform"><input type="date" value={visit.visit_date} onChange={e=>setVisit({...visit,visit_date:e.target.value})}/><input placeholder="进店支数" value={visit.units} onChange={e=>setVisit({...visit,units:e.target.value})}/><input placeholder="Decision maker" value={visit.decision_maker} onChange={e=>setVisit({...visit,decision_maker:e.target.value})}/><input placeholder="进货情况" value={visit.restock_status} onChange={e=>setVisit({...visit,restock_status:e.target.value})}/><textarea placeholder="Visit feedback / 当日动态" value={visit.feedback} onChange={e=>setVisit({...visit,feedback:e.target.value})}/><input placeholder="下次计划" value={visit.next_plan} onChange={e=>setVisit({...visit,next_plan:e.target.value})}/><label className="check"><input type="checkbox" checked={visit.test_case_placed} onChange={e=>setVisit({...visit,test_case_placed:e.target.checked})}/> 本次放 Test Case</label><button onClick={addVisit}><Plus size={14}/>记录本次拜访</button></div><div className="history">{visits.slice(0,showHistory?10:3).map(v=><div key={v.id}><b>{v.visit_date}</b> · {v.units}支 {v.decision_maker&&`· ${v.decision_maker}`}<p>{v.feedback||'无反馈备注'}</p></div>)}{visits.length>3&&<button onClick={()=>setShowHistory(!showHistory)}><History size={14}/>{showHistory?'收起':'查看最近 10 次'}</button>}</div></div>}
 <footer><button className="primary" onClick={saveShop}><Save size={15}/>保存门店</button>{draft.address&&<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${draft.name} ${draft.address} ${draft.city} FL`)}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/>谷歌地图</a>}</footer></div></div>}
 </main>}
function Field({label,children,wide}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}</label>}
